add fakeForEach and fakeIncludes.change the order of functions
erickaldiaz/fakeMDN pull request #47
Opened 2019-06-12 05:59 UTC by erickaldiaz

acá agregué las funciones corregidas, usando for of. También las ordené de acuerdo a la lista que paso Nico

2019-06-12 11:59 UTC, livchits requested changes

2019-06-12 11:59 UTC, livchits commented on app.js
Solo una sugerencia: que el `find = true` sea `return find = true`, de modo que si encuentra el elemento no siga iterando todo el array.
Ah, y habría que agregar el let y los puntos y comas que faltan.

2019-06-12 13:22 UTC, mborroni commented on app.js
O también podrias devolverle return true si entra en la condicion o return false y no tener un flag.

2019-06-14 06:57 UTC, erickaldiaz commented on app.js
listo, recién actualicé esto

2019-06-14 17:30 UTC, merged